# fly.toml app configuration file generated for lost-game-ai-assets-server on 2023-09-24T14:34:53-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lost-game-ai-assets-server"
primary_region = "atl"

[build]
  builder = "paketobuildpacks/builder:full"

[env]
  PORT = "8080"
  DB_PATH = "/data/lost.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="lost_assets_data"
  destination="/data"


